// <auto-generated />
namespace N.FourWar.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Users_DeleteColumns_Title_PasswordSalt : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207130655223_Users_DeleteColumns_Title_PasswordSalt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzXLTMBC+M8M7eHTHSksP0HFgStIwHUjTqQucFXuTaJAlI8kleTYOPBKvwMr/sZM2zQDDJRPLu99+u9pPK//68TN4u06Edw/acCWH5MQfEA9kpGIul0OS2cWLV+Ttm+fPgss4WXufK7uXzg49pRmSlbXpOaUmWkHCjJ/wSCujFtaPVEJZrOjpYPCanpxQQAiCWJ4X3GbS8gTyB3wcKRlBajMmpioGYcp1fBPmqN41S8CkLIIhufYnKtNfmPbHc+JdCM6QQwhiQbz07PyTgdBqJZdhyixn4m6TAr5fMGGgZHyenh1KenDqSFMmpbIIp+RRSZM6HUzoEhO3G0crT2pIkLFuW6DNB9hsLeDSjVYpaLu5hUXpdxUTj2770a5j7dbycaHxn7QvT4l3nQnB5gLqCmEJQ6s0vAcJmlmIb5i1oKXzhZx6L2onxuwis6s79RVkFQs3BLuJeBO+hvgjyKVd1fGmbF2tnA0G2FSfJMfuQy+rM2gTLJ4fju1+/33UG2bMd6Xjvx05oE3z9FsKNWQZx10rWZUqccuwtp0OK1xCsK0mNMRr8AtJ+Xlz7iRRh2u0SguxVqKme1QdTFmaYoFaKi9XvLCQ+OhF+HShJQUGjcwOvdVs60jY5GwJnbcYGplOuDZ2zCybM7dlozjpmR1W3CpYu8ZdYTclr6zd/7KdW0ed3z8n2qWbYDYJCjRPDGoGu46X0jGMmGB6xwExUiJL5L5D5iHvtvTbKO31w9EKMbdxipXDERphtlGa1T5SQDv17G4X7e1X5wjubv5D0uma1NFrCXWkEpRt+/iU7PVxYUI8LNE9j10PhxtjIfGdgR9+EyFovAaMwD9zs70ymzLJF2Bsvnt4Zrl3WzP3iHlIjYnF/zgUubTEe3T89WbmU+ehvGc6WjG9YxocP+7+GGh3mh0J/LRh1T92H59Xe8dV0epDEs8VJlEQLAfckZOsL7uAtq+wwRgMXzYQ7kIrIXI3xga0"
                       + "srmSC1XVHDNqM6pMOlsyBctiLMyFtnzBIouvIzAmv2R8ZiJDk8tkDvGVnGU2zeyFMZDMxdZVLaAPx8/H9TbnYJa6J/MnUkCaHFOAmXyXcRHXvCd9Ce2DcD1S6hJZ4SUL4ZabGulayQOByvKNIQXpVH0HSSoQzMxkyO5hP7fHa7hdsWDM2VKzxJQYjb/7oqLuk+rNb9n7X6OEDQAA"; }
        }
    }
}
