// <auto-generated />
namespace N.FourWar.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Init : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207171122584_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN0ayW7jNvReoP8g6FhgLGcaFG1gzyB1kjZosyDKTI8BLT3bRClKQ1Ku82099JP6C33UZkqUJdlJk7SXQUQ+vn33/P3nX5OPm4g5axCSxnzqHo3GrgM8iEPKl1M3VYt337sfP3z91eQ8jDbO5xLuWw2HL7mcuiulkhPPk8EKIiJHEQ1ELOOFGgVx5JEw9t6Pxz94R0ceIAoXcTnO5C7likaQfeDnLOYBJCol7CoOgcniHG/8DKtzTSKQCQlg6l6PLuJU/EbE6GzuOqeMEuTBB7ZwneT45JMEX4mYL/2EKErY/WMCeL8gTELB8UlyPJTp8XvNtEc4jxWii/lBQruVOCjQOQquHjVbmVBTFzkWJgTC/AKPtQM8uhVxAkI93sGieHcZuo5Xf+c1H1bPjDeaNP7F1XfHrnOdMkbmDCoNoQp9FQv4CTgIoiC8JUqB4PotZKxbVBs0tHXkl5QI6KfWjenmNFWr+/h34CUeNC36petc0A2EvwJfqlWF64psypPj8Rjd8xOn6Mf4SokUTOL5dzdt/e/LU70lUv4Ri/BnIlcvQP2arOky8+sGH7MVESRAu1OpaCBd5w5YBidXNMmjbaT99sECvBBxdBezwq+b9w8+OkegFRt3AN0TsQRV53bibQOnM5yaHL2ZyOq2/PkGvyhmXtgTz04bZnmlzXBNdeeAW8O13VuGawXax3CnUsYBzXhrt9xDS2I856EzhMk8cFqExZBJmaIJowHyNHW/sfTZQ6IU0SCR66+OdzwaHTX1YEjcrYjWyNrFZXeYdXN55DaD4YafAQMFzmmgskI/IzIgoe12aNVwL5ZaFNdjmyOLKIYoCF2FCMOOQSpBKFd2PFMe0ISwAQpqvB2YDbT4FZXmzRkkwHWpHKCMw8lXVBpW6dPQTi/MgxTfKHwBwqjl2GnpY9goywf1Ex+U4bZoxG241zzPCrP6Y8sXLDQWRAOjIdhOtEWuM0C7cmJT6wOzTyVai1SW"
                       + "JQemGwNnoeZmPNbFH6Ca9vptq6Y/Gw3PR31iDE8jw5XcoZqyNlVuv507vHzwKAcUb8eEMrkiSYLtmTGxFCeOn48rs3f+/kNDlOPw6ppuBmlFCRt2soTGLZJGTi+okOqMKDInunmYhZEFNizIS2JmrNu2K2O2hNZ/Fw21MbaN2sJrq7oLlCbSGTSbRBo+Yz/LpkTCiGhpyWYxSyO+O5Pufl0fY0w89ZvhGM1xxsRnng/Hlg8oJp78ZDiG+rBhYqrf2BgnXsNSVn2yPMHqHupuNcjp+pPQQPfrQTTAE3sx/DtOaU4JJhbz/OXNVc+vnTYrCvAwuxTAe+peV5DucbZWWm1tDbJbhqK9NzPoH8jazu70YJfq5Aozf0iz+eNS6nGzGjUHCNysrraDWEW2CVK5Z1VsG0V1UhS4/t2gVfFyENdB0dc01NXOf5QKopEGGPlfmA9iDWIGo2O90SzBrginC5Aqy8pTN7urbRoP2AJ6UobsLa4C53SJQ0IRZ117vz1XGm2LwJLWkzeBfE1EgLHTsgM7fNH3bEjb9ngHIv/vLL4OtK29+ToQUZWhdmEZrtwnLqe2RW6vFVHXOPi0pdbBi5OX2JD0d2M2yY7y++yrkWdY0L3WJu4JTtTqnv87P3rV7Zo9n/cv2Hbu1/JOZ+qG8xjNnCe89lXRM6ze2oi9pf2cqant5mCP7dszLZheYff2FsTeY69mt/YYZsZ/DsAol3S5RaGHFQ5BLcAqmEu+iMsYb3BUgjR6hitQJMToOxWKLlBYvA5AyuwH18+Epbo/ieYQXvKbVCWpQpEhmrPaj+A6X3TRz5aHdZ4nN0n2o9xziIBsUhQBbviPKWVhxfeF3TPtQqETUdH4a1sqPQAsHytM1zEfiKhQX5U/7yFKGCKTN9wna9jNW78O6xqbnFGyFCSSBY7te/xE9wujzYd/ADCCy9HeIgAA"; }
        }
    }
}
