// <auto-generated />
namespace N.FourWar.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Init : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207130644133_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzW7jNhC+F+g7CLqv6GRzaAN5F6kdF0HrOFhlt+exNLaJUqRKUqn9bD30kfoKHerfkp04Rnbbi2GRM998M5o//fPX3+HHbSq8J9SGKzn2L4KR76GMVcLleuzndvXuB//jh++/C2+TdOt9qeXeOznSlGbsb6zNrhkz8QZTMEHKY62MWtkgVimDRLHL0ehHdnHBkCB8wvK88FMuLU+xeKDHiZIxZjYHMVcJClOd001UoHr3kKLJIMaxfx/MVK5/Ax1Ml753IzgQhwjFyveyq+vPBiOrlVxHGVgO4nGXId2vQBisGF9nV6eSHl060gykVJbglDzLab9xhxy6JcftztEqnBr7xFh3JUjmF9ztHdDRg1YZarv7hKtK7y7xPbavx/qKjVpHx5mmf9K+v/S9+1wIWApsIkQhjKzS+DNK1GAxeQBrUUuniwX1gdWejcVNbjeP6neUtS16IZRNvjfjW0x+Rbm2m8beHLb1ydVoREn1WXLKPtKyOscuwfL5edvu99tbfQBj/lQ6+e8sRyDs17YesjZ1hwlNFWyBU85UzKoadce4tb38LlUitJ0SML7X4pcFHRSlcZBEY67tFKxsFXVLYUd6SjiHLKMAdXpMdeJFZYOZvIteX+ZpicFic6DaG7aNJSoxWGPvlkwT0xnXxk7BwhLcK5sk6UDstODWxrox7reVNuS1tPtfFVOn0QbDLtUN3Yy8Sak9FI5hw+BQc6sUoxgE6APtaaJEnspjLe457W7j6aJ0z09HK1tJF6c8OR2hbQtdlPb09UhlmR9CK2+GiCHrvaF+ArBBBvRGSj+dnivGvkhjvSnKXvGFVSG8PPUHlVGK+B6F6oknriqinbGYBk4giP4QEWpaayYYXLldpRabg+QrNLbIB+qC7m5vhzhjvjNjEvF/HPJcUlK8OM4HO8Br57t8Ah1vQB+YL+eP7zcD7U/nNwfuDt8zwV83W4dT4uXxenS6lnU09pOlIidKgtU8"
                       + "PnPwDms6ZN19P5yi4esWwm3/EmO3XregtcydXKk67uRRl1Et0nstc7SQUGButOUriC1dx2hMsRN9AZGTyG26xOROLnKb5fbGGEyXYm+vDdnz9ovtYp9zuMjck3kLF4gmJxdwIX/KuUga3rNhfR6DcDlSFT2xop2Q4Na7BuleyROBqvBNMUPpWsYjppkgMLOQETzhcW4vx3A/YuGUw1pDaiqMVt99fjL3/fnhX1oxEKaxDgAA"; }
        }
    }
}
