// <auto-generated />
namespace N.FourWar.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Users_AddColumn_FoursquareId : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207130808442_Users_AddColumn_FoursquareId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1X23LbNhB9z0z/gYP3ELKjySQeKhlXshpPIssTOukzRK4kTEGAAUBH+rY89JP6C13wJl4kWVbTTl88JrB79oI9u6u/fvwZvN8kwnsEbbiSI3LhD4gHMlIxl6sRyezy5Rvy/t0vL4KbONl4Xyu5V04ONaUZkbW16RWlJlpDwoyf8Egro5bWj1RCWazo5WDwll5cUEAIglieF3zOpOUJ5B/4OVYygtRmTMxUDMKU53gT5qjeHUvApCyCEbnzpyrTvzPtTxbEuxacoQ8hiCXx0uHVFwOh1UquwpRZzsTDNgW8XzJhoPT4Kh2e6vTg0jlNmZTKIpySZwVN6nAwoBsM3G6dW3lQI4Ie66YEynyEbesAj+61SkHb7WdYlnq3MfFoW492FWu1ho4zjf9J++qSeHeZEGwhoM4QpjC0SsNvIEEzC/E9sxa0dLqQu96z2rHhXsd8y5iGlrXXwz3WjiPNrzO7flB/gKxw8GmxLok35RuIP4Fc2XWNNWOb6mQ4GGB5fpEc6xi1rM6gabz4Pm7b/f3vrd4zY74rHX9gZv1vWw/orhT7BYqMtIxjDTReFTnnjmFjO/VaqIRgGyVtiLfDLwjq56W+14na3I75tKB+1SLogR4RzFiaYoIaPaM88cKiYYxfhs+nbVJg0MjsYW/tbW0JKcNW0LlF0+jplGtjJ8yyBXNPNo6Tnthpya2MNXPcbRO7lFfS7v+ypBuN0+93nWbqphhNgnTPA4Pag33NqlQMIyaY3tNuxkpkiTzUso5ptxtJE6d9czpis6E08Zrnp6MVLaKJU5ycjtCmexOpfdNHDGjnpbqFQHuV0BkV3bI6RsquSG29JmeHhEFJiKeneY8hhQjxMFWPPHbsCLfGQuI7AT/8JkLQuK6MwR+6HaQSmzHJl2Bs/orYDd1dazc4Y25TY2LxfxzeXFriPTmmnzlt983tBV/ltv7x4JaPTEdrpveMrPPn8k8D3Td2zwR/3lTtz4en"
                       + "B+vBuVowZ0TihcIgCgfLSXzmyO2zOKDNzT2YgOGrHYTb4yVEblHegVYyt3KpqrxjRE2PKpHOs8zAshgTc60tX7LI4nUExuTb0FcmMhS5SRYQ38p5ZtPMXhsDyUK0NtSAHref7xVtn4N56r7MzwgB3eQYAszlrxkXce33tE+jQxCuRkqao1e4DSLcalsj3Sl5IlCZvgmkIF2TeIAkFQhm5jJkj3DYt6dz2M5YMOFspVliSoydvvshSd0vyXd/A0nxDVR7DgAA"; }
        }
    }
}
