// <auto-generated />
namespace N.FourWar.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Users_AddColumn_Title : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207130645341_Users_AddColumn_Title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzW7jNhC+F+g7CLyv6GRzaAN5F6kdF0HrOFhlt2daGttEKVIlqdR+tj30kfoKHeqXluzEMdJtL4Y1nPnmRzMfR39//Sv6uM1E8ATacCXH5CIckQBkolIu12NS2NW7H8jHD99/F92m2Tb40ui9d3poKc2YbKzNryk1yQYyZsKMJ1oZtbJhojLKUkUvR6Mf6cUFBYQgiBUE0adCWp5B+YCPEyUTyG3BxFylIEwtx5O4RA3uWQYmZwmMyX04U4X+jelwuiTBjeAMY4hBrEiQX11/NhBbreQ6zpnlTDzucsDzFRMG6oiv86tTgx5duqApk1JZhFPyrKRJmw4mdIuJ250Lq0xqTDBi7Wugzi+w2xOg6EGrHLTdfYJVbXeXkoDu29G+YWvm2TjX+E/a95ckuC+EYEsBbYWwhLFVGn4GCZpZSB+YtaCls4Uy9IHXno/FTWE3j+p3kI0vfCHYTSSY8S2kv4Jc203rb862jeRqNMKm+iw5dh9aWV2AH2D1/Lxv9/vtvT4wY/5UOv3vPMdM2G/v/ZFb8a+XO6LdxAznCInDMo6tWodUU4MTw9b2xqoyicF6k2dI0OFXPBKWE3kwiNZdR1C0YqiGyegRKovmLM+xQB611ZIgrnht8i5+PbtkFQZNzAGSaaNtPeFkszX0TtE1Rjrj2tgps2zJ3CubpNlA7bTiNs78GvfZrCt5o+3+1zPs8Xs4JEe/dDPMJkNWKhODNoJDnFobxgkTTB9gxYkSRSaPMetz1j7f+Si+/HS0isF8nEpyOkLHRj5KJ309UsUuh9Cqk9MRa8bwoWrRECOivbfcbyI66KLebdhvyecGuq/Sem8HuzfAUT1MLy8sg+mqVEiAxXniqZuseGcsZKFTCOM/RAwaN7IJhFduzWrU5kzyFRhb9hQyqTvbW3/OWE2oMan4P+4nXGJjvbiJDNaX164m8onpZMP0gTvq/M3jzUD7i8WbA/t7w5uB760FZ6K+7tYf"
                       + "3l8vX/xH7/1qOsckXSpMogqw3hTOXAmGTBFR/wMomoLh6w7CfQ5JSNz3Rgfa6NzJlWoKjhn5ETUqvfcxB8tSLMyNtnzFEovHCRhTbmtfmChQ5TZbQnonF4XNC3tjDGRLsbfoR/R5/+Xesx9ztMjdk3mLFDBMjinAQv5UcJG2cc+GU38MwvVITSUYFW6rCLfetUj3Sp4IVJdvCjlIR0SPkOUCwcxCxuwJjsf2cg33KxZNOVtrlpkao7N33+PUfZB/+Ae15YMXwg8AAA=="; }
        }
    }
}
