// <auto-generated />
namespace N.FourWar.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Users_RenameColumn_Password : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207130729429_Users_RenameColumn_Password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzXLbNhC+dybvwME9hOz40HqoZFzJSj2tLE/opOcVuZIwAQEWAF3p2XroI/UVuhB/RJGSLWvSTi4eE9j99tvFfljon7/+jj6sMxk8obFCqyG7CAcsQJXoVKjlkBVu8fZH9uH9mx+i2zRbB19qu3fejjyVHbKVc/k15zZZYQY2zERitNULFyY645BqfjkY/MQvLjgSBCOsIIg+FcqJDLcf9DnSKsHcFSCnOkVpq3XaibeowT1kaHNIcMjuw4kuzO9gwvGcBTdSAHGIUS5YkF9df7YYO6PVMs7BCZCPmxxpfwHSYsX4Or86lfTg0pPmoJR2BKfVWUmzJh1K6JYSdxtPa5vUkBFj07Ygm19xs7dASw9G52jc5hMuKr+7lAV83493HRu3lo8PTf8p9+6SBfeFlDCX2FSIShg7bfAjKjTgMH0A59Ao74tb6r2onRizm8KtHvVXVHUsOhDqJhZMxBrT31At3aqJN4V1vXI1GFBTfVaCuo+8nCmwTbD8fj62//v/R30Aa//UJv0F7Oq/jh7xXQP124p05EDQyVXMKqX4ZVy7TpeVLjG6ViNaFuzwS1mF2wY9SKIJt9MrLwVbC5sfUXY0hTynArWUXq0EcSnz0dv49WLLSgye2AOaa9g2kajRYYmdXQpNTCfCWDcGB3PwRzZKs57ZacWtg7Vr3BX3ruS1tf+/aunWdRf274p26SaUTUYi3SaGDYNDV0zlGCcgwRy4JEZaFpk6dtE8592WfxulvX46WinoNk65cjrCvjjbSPs7fcSId+raPTbeO7fOddxtguck1DVpojdS6kgmqtr35YnZ6+fShAVUqieR+l6ON9ZhFnqDMP5DxmjoSTDC8MrP+dpsCkos0LrtKdLd5ff25u8Zs5Fbm8rvcUAK5Vjw4ijszc/Xzkb1BCZZgTkwFc4ffd8M9NBkOxP8dYOrfwW/PLuOjq6y3YcsnWtKoiRYDbszp1pfehFvP2mjMVqx3EH4"
                       + "B67CxL8gd6C1zZ1a6LrulFGbUW3SOZYpOkipMDfGiQUkjrYTtHb74PgCsiCT22yO6Z2aFS4v3I21mM3l3tMt4s/H347ufc7RLPdf9lukQDQFpYAz9XMhZNrwnvRldAzC90ilTWJFDy6CW24apHutTgSqyjfGHJVX9iNmuSQwO1MxPOFxbi/XcL9i0VjA0kBmK4ydv/+Fxf1PrPf/ArNaNl+UDQAA"; }
        }
    }
}
