// <auto-generated />
namespace N.FourWar.Db.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Characteristics_ColumnRename_Experience_To_Exp : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207231338515_Characteristics_ColumnRename_Experience_To_Exp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN0Z227bNvR9wP5B0OOAWnYXDFtgt8icZAu2xEGUdo8BLR3bxChKJSnX/rY97JP2CzvUzZIoS7Ljptlegpg8PPe7/vnr7/H7TcCsNQhJQz6xR4OhbQH3Qp/y5cSO1eLNj/b7d99+M77yg431MYf7XsPhSy4n9kqp6NxxpLeCgMhBQD0RynChBl4YOMQPnbfD4U/OaOQAorARl2WNH2KuaADJD/w5DbkHkYoJuw19YDI7xxs3wWrdkQBkRDyY2HeD6zAWfxAxuJzb1gWjBHlwgS1sKzo7/yDBVSLkSzciihL2uI0A7xeEScg4Po/O+jI9fKuZdgjnoUJ0IT9KaLsQBwW6QsHVVrOVCDWxkWNRhkCY32BbOcCjexFGINT2ARbZuxvftpzqO6f+sHhWeqNJ439c/XBmW3cxY2TOoNAQqtBVoYBfgIMgCvx7ohQIrt9CwrpBtUZDW0d+iomAFmpKxNCFaHYRq9Vj+CfwHA1aFt3Stq7pBvzfgS/VqmD8lmzyk7PhEL3zA6foxgWtw2jrvy9P9Z5I+TkU/q9Erl6A+h1Z02Xi1jU+pisiiIdmp1JRT9rWA7AETq5olAbbQLvtkwF4LcLgIWSZW9fvn1z0DU8rNmwBeiRiCarK7djZxU1rNNU5ejWB1W75q010IIK9xkvySZPF6npOAXcWa7o3LNYIdIjFLqQMPZrw1myyp4aEeMV9qw+TacQ0CIuxEjNFI0Y95Glif2fos4NELmKJRKq/Kt7hYDCq66EkcbsiGkNqH5ft8dXO5ciuR8GMXwIDBdaFp5ICPyXSI77pdmhV/yCWGhTXYZuRQRRjE4SuPoRhpyCVIJQrM5Ap92hEWA8F1d72TANa/IJK/eYSIuC6RPZQxvHkCyo1q3RpaK8XpkGKbxS+AFGq4dhh6WPYKMMH9RMXVMlt0Yi7cK94nhFm1ceGLxhoDIgaxpJge9Fmua4E2pYT61rvmX0K0RqkMizZM92UcGZq"
                       + "rsdjVfweqmku3KZqurNR/3zUJUb/NNJfyS2qyWtT4fa7ecNJB458MHH2TCbjWxJF2JeVJpXsxHLTMWX6xj18WAhSHE5V0/UgLShho06WULtF0sjpNRVSXRJF5kQ3D1M/MMD6BXlOrBzrpu3ymM2h9f9ZJ10a1wZN4bVT3TVKE+gMmkwgNZ8xnyXTIWFENPRi05DFAd+fSfe/ro4vZTzVm/4Yy3NMGV/5vD+2dDIp40lP+mOoThllTNUbE+PYqVnKqE+GJxjdQ9WtejlddxLq6X4diHp4YieGL+OUyXhQfp4cvLyBqhm11UpZye1niQz4QG3rmtE+uVaKqamtXpZKUDR3YyX6R7K2tx892olaucJc79Nk4riResAshsseAtfrqekgRlmtgxTuWZTXWhkdZyWtewto1LgUxLZQ9DX1dX1zt1JBMNAAA/cTc0GsQUxhcKZ3lznYLeF0AVIleXhiJ3eVneIR+z5HSp+9xqXfnC5xLMjirG3Dd+D2omnll9N67s6Pr4nwMHQatl3Hr/ROhrRpY3ck8v/Oiss07aE7riMxFJmpv4t9oTXUrrgdtAxqG/yet746ekXyEruQ7r7LJNlSdk++BDnBKu5r7dye4USN7vm/86OvukczJ/HuVdreTVra4Uxsfx6imdOE17wUOsGSrYnYa9rElTW12xEcsGc70SrpK2zZXoPYB2zQzJYew6z0+R+jXNLlDoUeUjh4lQArYG74IsxjvMZRDlLrGW5BER+j70IoukBh8doDKZNvqh8Ji3VjEszBv+GzWEWxQpEhmLPKZ26dL9roJ2vCKs/jWZR8fjuFCMgmRRFgxn+OKfMLvq/NnmkfCp2IsoZf21Lpxn+5LTDdhbwnokx9Rf58hCBiiEzOuEvWsJ+3bh1WNTa+pGQpSCAzHLv3+BPdzw827/4FSF0nd8AiAAA="; }
        }
    }
}
