// <auto-generated />
namespace N.FourWar.Db.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207231241393_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN0a227bNvR9wP5B0OOAWnYXDFtgt8icZAu2xEGUdo8BLR3bxChKJSnX/rY97JP2CzvUzZIoS7LjptleAps8PPe7889ff4/fbwJmrUFIGvKJPRoMbQu4F/qULyd2rBZvfrTfv/v2m/GVH2ysjznc9xoOX3I5sVdKReeOI70VBEQOAuqJUIYLNfDCwCF+6LwdDn9yRiMHEIWNuCxr/BBzRQNIvuDXacg9iFRM2G3oA5PZOd64CVbrjgQgI+LBxL4bXIex+IOIweXcti4YJciDC2xhW9HZ+QcJrhIhX7oRUZSwx20EeL8gTELG8Xl01pfp4VvNtEM4DxWiC/lRQtuFOCjQFQqutpqtRKiJjRyLMgTC/AbbygEe3YswAqG2D7DI3t34tuVU3zn1h8Wz0htNGj9x9cOZbd3FjJE5g0JDqEJXhQJ+AQ6CKPDviVIguH4LCesG1RoNbR35KSYCWqgpEUMXotlFrFaP4Z/AczRoWXRL27qmG/B/B75Uq4LxW7LJT86GQ/TOD5yiGxe0DqOt/7481Xsi5edQ+L8SuXoB6ndkTZeJW9f4mK6IIB6anUpFPWlbD8ASOLmiURpsA+22TwbgtQiDh5Blbl2/f3LRNzyt2LAF6JGIJagqt2NnFzet0VTn6NUEVrvlrzb4jWLihQPx7LVhklaaDFdXdwq4M1zTvWG4RqBDDHchZejRhLdmyz015MUr7lt9mEwDp0FYDJmYKRox6iFPE/s7Q58dJHIRSyRS/VXxDgeDUV0PJYnbFdEYWfu4bA+zdi5Hdj0YZvwSGCiwLjyV1PkpkR7xTbdDq/oHsdSguA7bjAyiGKIgdBEiDBsGqQShXJnxTLlHI8J6KKj2tmc20OIXVOo3lxAB15WyhzKOJ19QqVmlS0N7vTANUnyj8AWIUinHRksfw0YZPqifuKBKbotG3IV7xfOMMKs+NnzBQGNA1DCWBNuLNst1JdC2nFjXes/sU4jWIJVhyZ7p"
                       + "poQzU3M9Hqvi91BNc/02VdOdjfrnoy4x+qeR/kpuUU1emwq3340dTjp35POJs2dAGd+SKML2rDSwZCeWm04r0zfu4TNDkOJwqpquB2lBCft1soTaLZJGTq+pkOqSKDInunmY+oEB1i/Ic2LlWDdtl8dsDq0/Zw11aWobNIXXTnXXKE2gM2gyiNR8xnyWDImEEdHQkk1DFgd8fybd/7o6xZTxVG/6YyyPM2V85fP+2NIBpYwnPemPoTpslDFVb0yMY6dmKaM+GZ5gdA9Vt+rldN1JqKf7dSDq4YmdGL6MU5anhDKW8vnLm6uaX1ttlhXgfnbJgA/Uva4g7eNspbSa2upltwRFc29Won8ka3u706NdqpUrzPw+TeaPG6nHzWLU7CFwvbqaDmIU2TpI4Z5Fsa0V1XFW4LpXg0bFS0FsC0VfU19XO3crFQQDDTBwPzEXxBrEFAZneqGZg90SThcgVZKVJ3ZyV1k0HrEEdKT02WvcBM7pEoeELM7a1n4HrjSa9oA5recuAvmaCA9Dp2EFdvye72RIm9Z4RyL/7+y9TNMeufg6ElGRoPp72hfaTe1q3EEborZp8Hk7raP3Ji+xIOluxkySLdX35JuRE+znvtYi7hlO1Oie/zs/+qrLNXM8796v7V2vpY3OxPbnIZo5TXjNm6ITbN6aiL2m9VxZU7vFwQHLtxPtl77C6u01iH3AWs3s7DHMSv8agFEu6XKHQs8qHLxKgBUwN3wR5jFe4ygHqfUMt6CIj9F3IRRdoLB47YGUye+tHwmLdX8SzMG/4bNYRbFCkSGYs8pP4DpftNFPdodVnsezKPlN7hQiIJsURYAZ/zmmzC/4vjZ7pn0odCLK+n5tS6X7/+W2wHQX8p6IMvUV+fMRgoghMjnjLlnDft66dVjV2PiSkqUggcxw7N7jV3Q/P9i8+xdpyJ9/3CIAAA=="; }
        }
    }
}
