// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace N.FourWar.Web.Controllers {
    public partial class FoursquareController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FoursquareController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FoursquareController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Authorize() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Authorize);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FoursquareController Actions { get { return MVC.Foursquare; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Foursquare";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Foursquare";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Authenticate = "Authenticate";
            public readonly string Authorize = "Authorize";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Authenticate = "Authenticate";
            public const string Authorize = "Authorize";
        }


        static readonly ActionParamsClass_Authorize s_params_Authorize = new ActionParamsClass_Authorize();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Authorize AuthorizeParams { get { return s_params_Authorize; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Authorize {
            public readonly string code = "code";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_FoursquareController: N.FourWar.Web.Controllers.FoursquareController {
        public T4MVC_FoursquareController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Authenticate() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Authenticate);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Authorize(string code) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Authorize);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "code", code);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
